---
name: Docs 📚

on:
  push:
    branches:
      - main
    paths:
      - "inst/templates/**"
      - "_pkgdown.*"
      - DESCRIPTION
      - "**.md"
      - "**.Rmd"
      - "man/**"
      - "LICENSE.*"
      - NAMESPACE
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
    paths:
      - "inst/templates/**"
      - "_pkgdown.*"
      - DESCRIPTION
      - "**.md"
      - "**.Rmd"
      - "man/**"
      - "LICENSE.*"
      - NAMESPACE
  workflow_dispatch:

jobs:
  docs:
    name: Pkgdown Docs 📚
    uses: insightsengineering/r.pkg.template/.github/workflows/pkgdown.yaml@main
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
    with:
      default-landing-page: latest-tag
      additional-unit-test-report-directories: unit-test-report-non-cran
      deps-installation-method: setup-r-dependencies
      lookup-refs: |
        insightsengineering/osprey
        insightsengineering/formatters
        insightsengineering/rtables
        insightsengineering/rtables.officer
        insightsengineering/tern
        insightsengineering/teal.logger
        insightsengineering/teal.code
        insightsengineering/teal.data
        insightsengineering/teal.slice
        insightsengineering/teal.reporter
        insightsengineering/teal.widgets
        insightsengineering/teal.transform
        insightsengineering/teal
